### ISSUE TITLE
Duplicated data in GC_LISTING packet

### ISSUE THREAD

**Issue by TheDude-gh** [OpenTTD/game-coordinator#76]
As mentioned in #74 , the GC_LISTING packet returns lot of duplicated NewGRF entries.

With new system, I would expect there will be entires like this:
ID NEWGRF_ID NEWGRF_MD5 NEWGRF NAME

once for every unique combination. The ID is used in ServerInfo part to assign NewGRF to server.

What is observed is many duplicated combinations of the NEWGRF_ID NEWGRF_MD5 NEWGRF NAME, but with different ID.
Which is kind of redundant.

Seems like game controller does not properly check if the NewGRF already exists in the list.

At this moment there is ~6000 entries in the packet, while only ~1500 is actually unique, meaning 4500 entries are redundant.

Example of decoded GRF part from GC_LISTING packet

(removed attachment as it contains information we are not free to distribute)

**Comment by TrueBrain** [comment]
The packet in question is `NEWGRF_LOOKUP`, not `GC_LISTING`. The latter only returns indexes into the first table. The first returns the table. This to not confuse anyone looking into this :)

**Comment by TheDude-gh** [comment]
Cool.

> (removed attachment as it contains information we are not free to distribute)

What does this mean? The attached file did not contained any sensitive information, or did it?
